language: r
r: bioc-devel
sudo: false
cache: packages


env:
  global:
      - BIOC_USE_DEVEL="FALSE"
      
bioc_required: true
bioc_packages:
  - BiocInstaller

r_packages:
  - covr

after_script:
  - ./travis-tool.sh dump_logs

warnings_are_errors: false
 
